create view as vis_prestadores_contatos

SELECT 

m.cod_modulo,
m.txt_nome,
m.id,
m.dsc_modulo,
m.bln_coleta,

p.cod_prestador, 
p.txt_ano_cadastro, 
p.txt_nome, 
p.txt_sigla, 
p.txt_endereco, 
p.txt_bairro, 
p.txt_complemento, 
p.num_numero, 
p.num_cep, 
p.txt_site, 
p.num_inscricao_federal, 
p.num_inscricao_estadual, 
p.num_inscricao_municipal, 
p.txt_observacoes as txt_observacoes_prestador, 
p.txt_ultimo_ano_coleta, 
p.cod_municipio_fk as cod_municipio_prestador,
p.txt_tipo_prestador, 
p.txt_email,
p.txt_email2,
p.num_fone, 
p.num_fone2, 
p.num_fone3, 
p.num_fax, 

p.txt_mandatario_tratamento, 
p.txt_mandatario_partido, 
p.txt_mandatario_genero, 
p.txt_mandatario_sucessao, 
p.txt_mandatario_nome, 
p.txt_mandatario_cargo, 
p.txt_mandatario_email, 
p.txt_mandatario_email2, 
p.num_mandatario_fone, 
p.num_mandatario_fone2, 
p.num_mandatario_fone3, 
p.num_mandatario_fax, 

p.txt_substituto_tratamento, 
p.txt_substituto_partido, 
p.txt_substituto_genero, 
p.txt_substituto_sucessao, 
p.txt_substituto_nome, 
p.txt_substituto_cargo, 
p.txt_substituto_email, 
p.txt_substituto_email2,
p.num_substituto_fone, 
p.num_substituto_fone2, 
p.num_substituto_fone3, 
p.num_substituto_fax,

mp.cod_modulo_prestador, 
mp.txt_secretaria_nome, 
mp.txt_secretaria_endereco, 
mp.txt_secretaria_bairro, 
mp.num_secretaria_numero, 
mp.txt_secretaria_complemento,
mp.num_secretaria_cep, 
mp.txt_secretaria_site, 
mp.txt_secretaria_email, 
mp.txt_secretaria_email2, 
mp.num_secretaria_fone,
mp.num_secretaria_fone2, 
mp.num_secretaria_fone3,
mp.num_secretaria_fax, 
mp.cod_municipio_fk as cod_municipio_modulo_prestador, 

mp.txt_encarregado_tratamento, 
mp.txt_encarregado_partido, 
mp.txt_encarregado_genero, 
mp.txt_encarregado_sucessao, 
mp.txt_encarregado_nome, 
mp.txt_encarregado_cargo, 
mp.txt_encarregado_email, 
mp.txt_encarregado_email2, 
mp.num_encarregado_fone, 
mp.num_encarregado_fone2, 
mp.num_encarregado_fone3, 

mp.txt_outro_tratamento, 
mp.txt_outro_partido,
mp.txt_outro_genero, 
mp.txt_outro_sucessao, 
mp.txt_outro_nome, 
mp.txt_outro_cargo, 
mp.txt_outro_email, 
mp.num_outro_fone, 
mp.num_outro_fone2,  
mp.txt_outro_email2, 
mp.num_outro_fone3, 
mp.txt_observacoes as txt_observacoes_modulo_prestador

FROM public.tab_prestadores p
JOIN public.rlc_modulos_prestadores mp on (p.cod_prestador=mp.cod_prestador_fk)
JOIN acesso.tab_modulos m on (mp.cod_modulo_fk=m.cod_modulo)